name: jupyterlab-dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  # runtimes
  - nodejs >=18,<19
  - python =3.11
  # package managers
  - pip
  - yarn >=3,<4
  # build
  - hatch-jupyter-builder >=0.3.2
  - hatchling >=1.5.0
  # run
  - async-lru >=1.0.0
  - ipykernel
  - jinja2 >=3.0.3
  - jupyter_core
  - jupyter_server >=2.4.0,<3
  - jupyter-lsp >=2.0.0
  - jupyterlab_server >=2.19.0,<3
  - notebook-shim >=0.2
  - packaging
  - tornado >=6.2.0
  - traitlets >=5.10.1
  # test
  - coverage
  - pytest >=7.0
  - pytest-check-links >=0.7
  - pytest-console-scripts
  - pytest-cov
  - pytest-jupyter-server >=0.5.3
  - pytest-timeout
  - pytest-tornasync
  - requests
  - requests-cache
  - virtualenv
  # dev
  - black-jupyter
  - bump2version
  - hatch
  - pre-commit
  - pytest-cov
  - python-build
  - ruff
  # demo
  - jupyter-server-proxy
  - matplotlib-base
  - notebook >=7.0.4
  - numpy
  - vega_datasets
  - xeus-python
  # extra conda stuff
  - jsonschema-with-format-nongpl
  # jupyter-collaboration 1.2.0
  - jupyter_ydoc >=1.0.1,<2.0.0
  - ypy-websocket >=0.12.1,<0.13.0
  - jupyter_events >=0.7.0
  - jupyter_server_fileid >=0.7.0,<1
  - pip:
    # can't be installed with `conda` in binder, due to `jupyterlab-link-share``
    - jupyter-collaboration ==1.2.0
