name: Linux JS Flaky Tests

on:
  push:
    branches: [3.6.x]
  pull_request:
    branches: [3.6.x]
  release:
    types: [published]

jobs:
  linuxjs:
    name: JS
    strategy:
      matrix:
        group: [js-apputils, js-services]
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        env:
          GROUP: ${{ matrix.group }}
        run: |
          bash ./scripts/ci_install.sh

      - name: Run test ${{ matrix.group }}
        env:
          GROUP: ${{ matrix.group }}
        run: |
          bash ./scripts/ci_script.sh
